// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiKYAMyERS-7WIxuKbqLYl6teVbnHZ45w',
    appId: '1:473272273160:web:54c4bb1833613df9bfc4bd',
    messagingSenderId: '473272273160',
    projectId: 'furniture-app-bb60b',
    authDomain: 'furniture-app-bb60b.firebaseapp.com',
    storageBucket: 'furniture-app-bb60b.firebasestorage.app',
    measurementId: 'G-7ZFPB34JZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnsblcF3LxtNlPVIO_ZN6OuDYYYVkPmkI',
    appId: '1:473272273160:android:75d2d0bc8019a014bfc4bd',
    messagingSenderId: '473272273160',
    projectId: 'furniture-app-bb60b',
    storageBucket: 'furniture-app-bb60b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI-VnBzAvyE0e2zKEtYA8d4ZSuz-Qd4PY',
    appId: '1:473272273160:ios:d718ce00a6e45194bfc4bd',
    messagingSenderId: '473272273160',
    projectId: 'furniture-app-bb60b',
    storageBucket: 'furniture-app-bb60b.firebasestorage.app',
    iosBundleId: 'com.example.finalFurniture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiKYAMyERS-7WIxuKbqLYl6teVbnHZ45w',
    appId: '1:473272273160:web:54c4bb1833613df9bfc4bd',
    messagingSenderId: '473272273160',
    projectId: 'furniture-app-bb60b',
    authDomain: 'furniture-app-bb60b.firebaseapp.com',
    storageBucket: 'furniture-app-bb60b.firebasestorage.app',
    measurementId: 'G-7ZFPB34JZ3',
  );

}